import type { Attachment, CanvasArtifactEntry } from '../types'

export type DriveFileKind = 'document' | 'image' | 'code' | 'artifact'
export type DriveFileSource = 'upload' | 'artifact'

export interface DriveFile {
  id: string
  name: string
  kind: DriveFileKind
  size: string
  sourceChat: string
  updatedAt: string
  /** Whether the file was uploaded by the user or generated by Grizon. */
  source: DriveFileSource
  /** Name of the project this file belongs to, when grouped under one. */
  project?: string
  conversationId?: string
  mimeType?: string
  artifactType?: string
}

/** Project uploads — empty until the projects API is wired. */
export function getProjectUploads(_projectName: string): Attachment[] {
  return []
}

/** Project artifacts — empty until the projects API is wired. */
export function getProjectArtifacts(_projectName: string): CanvasArtifactEntry[] {
  return []
}
